#! /usr/bin/env python
# -*- coding: utf-8 -*-

#Définit la configuration du module Connector

#Logger
IMDB_FILM_STATUS_CONNECTOR_LOGGER_NAME = "IMDB FILM STATUS CONNECTOR"
IMDB_PERSON_STATUS_CONNECTOR_LOGGER_NAME = "IMDB PERSON STATUS CONNECTOR"
IMDB_COMPANY_STATUS_CONNECTOR_LOGGER_NAME = "IMDB COMPANY STATUS CONNECTOR"
